definitionsを定義
team-maker-developers/team-maker-api pull request #1
Opened 2019-09-01 00:42 UTC by daisuke85a

2019-09-02 05:09 UTC, nuno929 requested changes

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +      info:
スキーマは応募者IDと求人ID、ステータスIDのみで十分かと思います。

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +  JobOffer:
Jobだけで問題ないのでは？

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +      # corporation: 必要か迷ったが削除。GETをGraphQLで行う前提だと不要と考えた。
`GraphQL` でやる想定ですが、リレーション定義がAPI仕様書から見えなくなりますので、この辺は記載していただけないでしょうか？

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +      other:
infoでお願いでますか？ json型で格納する項目名は、実装の都合上統一したいです。

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +        type: "string"
json型の場合、typeはobject型になるかと思います。
stringでも間違ってはいないのですが...

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +      point:
pointは別モデルにしていだけないでしょうか？

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +      tag:
tagはemployee全体で共通するので、不要です。
やるなら、Settingモデルを作るとかになりますね...

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +      passwordConfirm:
confirmをモデルに入れるのは、なぜでしょうか？

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +      name:
`かな` もあった方がよろしいかと思います

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +        description: "ID情報。管理者が任意の文字に指定する。会社用のメアドを持たない社員が多いと想定しemailは使わない。"
ID任意って、必須でしょうか？ かなりリスクが高い機能になるかと思います。

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +  Administrator:
`Administrator` と `Employee` をわける理由がわからないです。
`role` のような項目をもたせて、権限分割すれば、いいのではないでしょうか？

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +  Corporation:
`Company` でいいのでは？

単純に字数の問題です。
スペルミスによるバグ発生率もバカにならないので。

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +      department:
部署わけするなら、別モデルに切り出して欲しいです。

2019-09-02 05:09 UTC, nuno929 commented on swagger.yaml
> +    description: "社員から紹介された求人応募情報"
別途、応募者情報用のモデルが欲しいです。

2019-09-02 05:11 UTC, nuno929 commented
@daisuke85a 
細かくつっこんでいくと、終わらない気がしました...
一旦、モデル単位で意識あわせしませんか？

必要なモデルを洗い出していただけると助かります。

2019-09-02 06:54 UTC, daisuke85a commented on swagger.yaml
> +        type: "string"
object型の方が適切ということですね。理解しました。修正します。

2019-09-02 06:54 UTC, daisuke85a commented on swagger.yaml
> +      other:
承知しました。

2019-09-02 06:54 UTC, daisuke85a commented on swagger.yaml
> +  JobOffer:
Jobだけにします。シンプルですね。

2019-09-02 06:54 UTC, daisuke85a commented on swagger.yaml
> +      point:
承知しました。

2019-09-02 06:57 UTC, daisuke85a commented on swagger.yaml
> +      passwordConfirm:
DBのモデルにはconfirmは不要と思っています。
ですが、フロントからバックエンドにPOSTする際は、confirmも含めてPOSTするかと考えて、
swagger上にはconfirmを加えています。

「DBのモデル」をそのまま「swaggerのdefinitions」にするのが適切なのでしょうか？
（基本的なところですみません。）

2019-09-02 06:58 UTC, daisuke85a commented on swagger.yaml
> +      name:
承知しました。

2019-09-02 07:02 UTC, daisuke85a commented on swagger.yaml
> +  Administrator:
>role のような項目をもたせて、権限分割すれば、いいのではないでしょうか？
DBのモデル上は上記を考えていました。

swaggerのdefinitionsでは、POSTするときの情報が異なる（Adminだとemailが必要、Employeeだと不要）ので、API利用者にとってわかりやすくなるようにAdministrator と Employee をわけてみました。

が、DBとswaggerの定義がずれるほうが、わかりにくいようですね💦逆効果でした、すみません。
修正します。

2019-09-02 07:03 UTC, daisuke85a commented on swagger.yaml
> +  Corporation:
` Company`に修正します

2019-09-02 07:06 UTC, daisuke85a commented on swagger.yaml
> +      # corporation: 必要か迷ったが削除。GETをGraphQLで行う前提だと不要と考えた。
承知しました。 
$refではなく、type: integerのidを記載しようと思います。
idをどのモデルが持つか、を示すことで、DBのモデルの関係性を示せてわかりやすいかと考えました。

2019-09-02 07:06 UTC, daisuke85a commented on swagger.yaml
> +      info:
承知しました。

2019-09-02 07:06 UTC, daisuke85a commented on swagger.yaml
> +    description: "社員から紹介された求人応募情報"
追加します。

2019-09-02 07:11 UTC, daisuke85a reviewed
@nuno929 
ご指摘ありがとうございます。

>一旦、モデル単位で意識あわせしませんか？
>必要なモデルを洗い出していただけると助かります。

承知しました。まずはモデルの洗い出しから始めます。
品質が低く申し訳ないです💦

2019-09-02 07:11 UTC, daisuke85a commented on swagger.yaml
> +      department:
承知しました。モデルの切り分けが甘いですね。。💦

2019-09-02 07:11 UTC, daisuke85a commented on swagger.yaml
> +        description: "ID情報。管理者が任意の文字に指定する。会社用のメアドを持たない社員が多いと想定しemailは使わない。"
誤解を招く書き方をしてしまいました、すみません。
IDデータは必須で持つ情報です。ただし、任意というのは「ユーザーが好きなように入力できる」という意味で使いました。descrptionを修正します。

2019-09-02 07:14 UTC, nuno929 commented on swagger.yaml
> +      # corporation: 必要か迷ったが削除。GETをGraphQLで行う前提だと不要と考えた。
@daisuke85a 
1対多や中間テーブルの場合は、どのようにしますか？
$refの方がいいかと思います。

2019-09-02 07:16 UTC, nuno929 commented on swagger.yaml
> +        description: "ID情報。管理者が任意の文字に指定する。会社用のメアドを持たない社員が多いと想定しemailは使わない。"
すいません。ユーザーが好きなように採番する機能って、必須の機能かどうかを確認しております。多分、誤解はないです。
IDは外部キーになるので、新規登録の場合はいいですが、更新を想定するとかなり危険な機能になるかと思います。

2019-09-02 07:19 UTC, nuno929 commented on swagger.yaml
> +  Administrator:
POSTする時の情報が異なるかは、実装次第かと思います。
モデルが増えれば増えるほど、APIの仕様理解は難しくなりますので、わけない方がいいです。

2019-09-02 07:22 UTC, nuno929 commented
> 承知しました。まずはモデルの洗い出しから始めます。
> 品質が低く申し訳ないです💦
最終的に、いいものができればいいんで、大丈夫です！

2019-09-02 08:29 UTC, nuno929 requested changes
ご確認よろしくお願いたします！

2019-09-02 08:29 UTC, nuno929 commented on swagger.yaml
> +      introducer:
ここは悩みどころですね...
応募者に紐づけてもいい気もします。

2019-09-02 08:29 UTC, nuno929 commented on swagger.yaml
> +      user:
ポイントは、statusを元に計算すると思うので、Userへの紐付けは不要かと思います。

あわせて、ユーザーには金額を見せた方がいいかと思うので、 
`Point` より `Incentive` の方がよろしいかと思います。

2019-09-02 13:07 UTC, daisuke85a commented on swagger.yaml
> +        description: "ID情報。管理者が任意の文字に指定する。会社用のメアドを持たない社員が多いと想定しemailは使わない。"
>すいません。ユーザーが好きなように採番する機能って、必須の機能かどうかを確認しております。多分、誤解はないです。
そういうことですか。承知です。
確かに、ユーザーが好きなように採番する機能は不要ですね。社員はLINE認証が必須になったはずなので、ユーザーIDは「LINEのアカウントIDを使う」とかも良いかと思いました。

2019-09-02 13:22 UTC, daisuke85a commented on swagger.yaml
> +      user:
確かにですね。修正します！

2019-09-02 13:49 UTC, daisuke85a commented on swagger.yaml
> +      introducer:
確かにですね。応募者に紐付けたほうがシンプルで応用がききやすい気がしました。
応募者に紐付けます。

2019-09-02 13:53 UTC, daisuke85a commented
@nuno929 
ひとまずモデルと関係性について、ご指摘に対し対応いたしました。
ご確認をよろしくお願いいたします。

2019-09-02 15:04 UTC, nuno929 approved these changes
OKです！ 一旦、ここでマージしますね。

2019-09-02 15:04 UTC, nuno929 commented on swagger.yaml
> +        description: "#応募/面談/内定/削除 などのステータス"
@daisuke85a 
細かいですが、削除はフラグ管理が一般的なので、不要かと思います。

2019-09-02 15:04 UTC, merged

2019-09-02 15:07 UTC, nuno929 commented
@daisuke85a 
ちなみにですけど、masterにマージしないのは理由がございますか？

2019-09-03 01:43 UTC, daisuke85a commented on swagger.yaml
> +        description: "#応募/面談/内定/削除 などのステータス"
確かにですね！消しておきます💦

2019-09-03 01:46 UTC, daisuke85a commented
@nuno929 
マージありがとうございます！

>ちなみにですけど、masterにマージしないのは理由がございますか？

リリースするタイミングでmasterにマージする運用を考えていました。
それまではdevelopにマージしようかなと。

ただ、あまりこだわりはありません。しっかりとしたチームでGitを運用したことがないので・・・
オススメ運用法があれば、教えていただけたら幸いです！

2019-09-03 03:46 UTC, nuno929 commented
@daisuke85a 
開発環境と本番環境をわけて、運用する想定なので、常にmasterにマージしても問題ないです。
※ masterにバグがあっても、本番環境には影響しない

逆に謎のルールが増える方がややこしい + circle_ciなどの実装工数が増えるので、masterにマージしていく方針で問題ないかと思います。

2019-09-03 04:11 UTC, daisuke85a commented
@nuno929 
承知しました。
developブランチを削除して、順次masterにマージしていく方針にします！
ありがとうございます〜