求人レコードの取得エンドポイントの仕様追加
team-maker-developers/team-maker-api pull request #12
Opened 2020-02-28 11:48 UTC by bumptakayuki

https://github.com/TEAMMAKER-dev/team-maker-back/issues/106 のAPIの仕様を追加しました。認識があっているかみていただけると幸いです 🙏 

https://www.chatwork.com/#!rid176972051-1285139273560924160 でコメントいただいた内容は反映していますが、不足点あるようでしたらコメントいただけると幸いです。

また、いくつか懸念/疑問点があるので、質問させていただきたいです

### 質問

- いったん テーブル（pages、jobs）が持っているデータをそのままAPIで返すような感じにしていますが、APIで返す際に不要なものがあったら教えていただきたいです。例えば、 metaカラム（メタタグの内容を記載する）に格納されてるデータがいまいちイメージつかなかったのですが、必要ではなかったりしますでしょうか。

- いったん、テーブルが持っているデータをそのまま返しているというところで、例えば、compay_idなどを返すようになっていますが、こちらは加工して、comany オブジェクトにする必要などあったりしますでしょうか？

- タイプ（ポリもーフィックリレーションのタイプ。例えば、job、施設情報など）ごとに、レスポンスの中身（コンテンツ）は変わる想定でしょうか？このPRでいうところの `pageable_content ` の `type` 部分です。タイプが変わると、`record ` オブジェクトの内容が変わりそうかと思っていて、変わりそうな場合、エンドポイント分けたほうが良さそうでは？と思ったりしています。（変わらない場合は、そのままで大丈夫そうに思うのですが、、認識が異なりそうであれば教えていただけると幸いです）

2020-02-28 20:51 UTC, TEAMMAKER-dev commented
> いったん テーブル（pages、jobs）が持っているデータをAPIで返すような感じの想定をしていますが、APIで返す際に不要なものがあったら教えていただきたいです。例えば、 metaカラム（メタタグの内容を記載する）に格納されてるデータがいまいちイメージつかなかったのですが、必要ではないなどあったりしますでしょうか。
→ metaカラムは、メタタグなんで絶対に必要ですね。
migrationのコメントにも記載しているのですが、なぜ不要と思うのでしょうか？ 求人票のタイトルタグなどは必須だと思うのですが...

2020-02-28 20:56 UTC, TEAMMAKER-dev commented
> また、compay_id などを返すようになっている部分もありますが、こちらは加工して comany オブジェクトにする必要などあったりしますでしょうか？（front側では、companyのnameが必要だったりするかと思ったりしている感じです）

→ 以下の内容はcompanyオブジェクトにする必要があるという意味で記載しております。
ただ、セキュリティ上、companyオブジェクトの全項目を表示するのはまずいですね...
> 外部キーについて
外部キー項目とは別途、外部キー用のobjectも取得した状態で、レスポンスを返したい
フロント側で、別途、外部キーに関連するデータを取得する処理を実装するのはやりたくない

2020-02-28 20:59 UTC, TEAMMAKER-dev commented
> タイプ（ポリモーフィックリレーションのタイプ。例えば、job、施設情報など）ごとに、レスポンスの中身（コンテンツ）は変わる想定でしょうか？このPRでいうところの pageable_content の type 部分です。タイプが変わると、record オブジェクトの内容が変わりそうかと思っていて、変わりそうな場合、エンドポイント分けたほうが良さそうでは？と思ったりしています。（変わらない場合は、そのままで大丈夫そうに思うのですが、変わりそうかと思っています。認識が異なりそうであれば教えていただけると幸いです）

→ 変わるのですが、エンドポイントを分けた方いいと思うのは、なぜでしょうか？
求人票を表示する際のスループットが長くなるので、よろしくないと考えております

2020-02-28 21:15 UTC, nuno929 requested changes

2020-02-28 21:15 UTC, nuno929 commented on docs/swagger.yaml
> +    description: ローカルサーバ
ローカルサーバの情報はできれば、表示したくないです。

2020-02-28 21:15 UTC, nuno929 commented on docs/swagger.yaml
> +      bearerFormat: JWT
Auth定義は不要ですね

2020-02-28 21:15 UTC, nuno929 commented on docs/swagger.yaml
> +  "/api/v1/page/{id}":
すいません。こちら、私の要件挙げが漏れておりましたが、pageのルートキーは、文字列の方がいいですね...
ユーザー側で求人票のURLを可変にしたいので、ユーザー定義の文字列をルートキーにしたい次第です。

pagesテーブルにカラムの追加もお願いして、よろしいでしょうか？

2020-02-28 21:15 UTC, nuno929 commented on docs/swagger.yaml
> +                          record:
Swaggerはモデル定義を使い回せるので、その機能を使用してください。
https://qiita.com/teinen_qiita/items/e440ca7b1b52ec918f1b#components

2020-02-29 00:04 UTC, bumptakayuki commented
認識や前提が異なっていたらすいません 🙏 こちらのコメントについてもう少し教えていただきたいです！

https://github.com/team-maker-developers/team-maker-api/pull/12#issuecomment-592725418

> 求人票を表示する際のスループットが長くなる

現状の想定だと以下のパターンのコンテンツがあり、それぞれエンドポイントを分けたほうが良さそうと思っている感じなのですが、

- 求人票コンテンツを表示させるためのAPI
- 施設情報コンテンツを表示させるためのAPI
- ユーザーがwysiwygエディタで作成したコンテンツを表示させるためのAPI

例えば、エンドポイントを分けたとして、求人票コンテンツを表示させるためのAPIのスループットが長くなる理由がいまいち理解できていないです。（それぞれ別のコンテンツなので１リクエスト？など思ったりしています）読解力不足ですいません... もう少し教えていただけると幸いです 🙏 

エンドポイントを分けたいと思った理由は、`pageable_content` の  `record` の内容が、コンテンツのタイプごとに異なると思うので、API仕様書の書き方が複雑になりそうかと思った感じです。今はjobの場合に合わせて書いてるかと思うのですが、例えば、施設情報コンテンツの場合は、この`record` の内容が仕様書通りにならなそうということを懸念しています。

エンドポイントを分けるというのは以下のようなイメージだったりしています

```
GET “/api/v1/page/jobs/{slug}“:
GET “/api/v1/page/facilities/{slug}“:
GET “/api/v1/page/wysiwyg/{slug}“:
```

そもそもの前提が把握できていなそうだったり、認識が間違っていそうな部分がありそうでしたらコメントいただけると幸いです。お手数お掛けしますが、よろしくお願いします 🙏

2020-02-29 01:36 UTC, bumptakayuki commented on docs/swagger.yaml
> +                          record:
なるほどですね！ありがとうございます 🙏

2020-02-29 01:50 UTC, nuno929 commented
> 求人票コンテンツ
施設情報コンテンツ
ユーザーがwysiwygエディタで作成したコンテンツ

プロトタイピングの段階なので、変更不可能な前提はないですね...
pagableもfixした要件ではないので、変更可能です。

求人コンテンツと施設コンテンツを1ページに表示する場合もあると考え、現状の仕様にしている次第です。捨ててもいい仕様ではあります。

あわせて、ユーザーがwysiwygエディタで作成したコンテンツは、HTMLを入力する想定です。
求人票の項目はHTMLを許容したくないので、こちらは分割したいです。

2020-02-29 02:13 UTC, bumptakayuki commented
@nuno929 なるほどですね！ありがとうございます。

ちょっと今気にしてる部分としては、エンドポイント `GET /api/v1/page/{slug}` に対してのAPI仕様が、以下のようになっていると、`pageable_content ` の `type` が `job` 以外の場合、仕様が正しくなくなるんじゃないかなってところですね、、、（`job`以外の場合、例えば`facilities `とかだと、`record`の部分を `$ref: '#/components/schemas/Facility'` とかにすれば良さそうという話かもしれないですが、条件分岐させて記述できる？などが分かっておらず気になっています）

```
pageable_content:
 properties:
   type:
     title: コンテンツのタイプ
     type: string
     enum: [job, facilities, wysiwyg]
     example: job
  record:
     $ref: '#/components/schemas/Job'
```


とはいえ、プロトタイピングの段階とのことで、いったんは `job` を返すパターンで作って、必要になったときにまた検討するというような感じで大丈夫そうですかね...（なので、このPRの内容で大丈夫そうだったら、いったんこの内容を返すAPIを作ろうと思います！）

2020-02-29 02:21 UTC, nuno929 commented
@bumptakayuki 
現状の問題点は、API仕様書の書き方になりそうですね。
こちらは、コメントなどで工夫することもできると思いますので、
一旦は棚上げで大丈夫です！

2020-02-29 02:24 UTC, bumptakayuki commented
@nuno929 承知しました！ありがとうございます 🙏

2020-03-02 06:35 UTC, nuno929 requested changes

2020-03-02 06:35 UTC, nuno929 commented on docs/swagger.yaml
> +              schema:
pageもcomponentsで定義していただけませんか？

2020-03-02 06:35 UTC, nuno929 commented on docs/swagger.yaml
> +                  company:
companyもcomponentsで定義していただけませんか？

2020-03-02 06:35 UTC, nuno929 commented on docs/swagger.yaml
> +                      pageable_content:
ここはポリモーフィックと明記していただけますか？
また、仕様書が正確ではない問題は下記のように記載すれば、わかるようになるかと思います。
 - pageable_contentは、  `{ type,  record }` の連想配列だけ仕様書に記載。別途、jobなどが入りうる旨だけを補足
- pageable_contentとは、別にjobプロパティを記載する

2020-03-02 06:35 UTC, nuno929 commented on docs/swagger.yaml
> +components:
componentsに寄せたいので、definitionsの削除をよろしくお願いいたします。

2020-03-02 06:35 UTC, nuno929 commented on docs/swagger.yaml
> +                            enum: [job, facilities, wysiwyg]
`facilities, wysiwyg` は実装していないので、削除していただけませんか？

2020-03-02 06:35 UTC, nuno929 commented on docs/swagger.yaml
> +          type: number
コードなので、numberではないです...
0010などはnumberにならないので。

2020-03-02 06:35 UTC, nuno929 commented on docs/swagger.yaml
> +          example: 1
取得結果もレスポンスに返してください

2020-03-02 06:35 UTC, nuno929 commented on docs/swagger.yaml
> +              example:
`contract_period` の中身は、finished_atなどで、固定にしない想定ですね...

2020-03-02 08:25 UTC, bumptakayuki commented on docs/swagger.yaml
> +                      pageable_content:
こちらもう少し教えていただきたいのですが、`title` をポリモーフィックと記述すれば良さそうな感じでしょうか... 🙏

2020-03-02 08:27 UTC, bumptakayuki commented
@nuno929 指摘いただいた箇所修正しました 🙏 

https://github.com/team-maker-developers/team-maker-api/pull/12/commits/dde35f0ceabf868b3a81ce49787a5b269c0551c4

https://github.com/team-maker-developers/team-maker-api/pull/12#discussion_r386215409 の部分だけ、変更内容のイメージの認識が合ってるかみていただけると助かります 🙏 （上記 commit にはtitleをポリモーフィックと記述するように修正を含めています）

2020-03-02 08:34 UTC, nuno929 commented on docs/swagger.yaml
> +              title: ポリモーフィック
イメージ的にはあっているんですが、 `ポリモーフィック関連で結びつくモデルがセットされる。各モデルのスキーマは、別プロパティに詳述する。 ex) jobが紐づく場合は、jobになる` を追記していただければと思います。

2020-03-02 08:35 UTC, nuno929 commented on docs/swagger.yaml
> +                      pageable_content:
@bumptakayuki 

こちらの件、イメージ的にはあっているんですが、 `ポリモーフィック関連で結びつくモデルがセットされる。各モデルのスキーマは、別プロパティに詳述する。 ex) jobが紐づく場合は、jobになる` を追記していただければと思います。

2020-03-02 08:45 UTC, bumptakayuki commented on docs/swagger.yaml
> +                      pageable_content:
@nuno929 なるほどですね。ありがとうございます 🙏 こちらのコメントそのまま使わせていただきました 🙇 

https://github.com/team-maker-developers/team-maker-api/pull/12/commits/bb3b4bee9f73531147f6b6f3c766f54c8eef6ab1

2020-03-02 09:21 UTC, nuno929 approved these changes
@bumptakayuki 
大枠はOKですが、荒削りですね...

一旦、大枠の実装には影響しないので、titleとdescription、exampleなどを精査するissueを別途作成していただけませんか？

2020-03-02 09:22 UTC, merged