全テーブルにCompanyを持つ。紹介者をApplicationに移動
team-maker-developers/team-maker-api pull request #5
Opened 2019-09-04 13:11 UTC by daisuke85a

DBの修正に合わせて、swaggerの定義も修正する
修正点は２点
- 全テーブルにCompanyを持つ。
- 紹介者をApplicantからApplicationに移動

詳細は以下を参照のこと
https://github.com/nuno929/team-maker-back/pull/5

2019-09-04 13:15 UTC, nuno929 requested changes
companyをまたぐユーザーはいないので、job以外の  `$ref: company` は不要かと思います。

2019-09-04 13:24 UTC, daisuke85a commented
> companyをまたぐユーザーはいないので、job以外の `$ref: company` は不要かと思います。

確かに、Frontには不要なデータかと思うので、削除しても問題ないとは思います。
一方で、以前に @nuno929 さんから「DBとswaggerの定義は同じままに保ちたい（大規模になった時にも可読性を保つため）」というご指摘を受けた気がしていて、ちょっと混乱中です💦

上記もふまえても、job以外の `$ref: company` は削除して問題ないでしょうか？

2019-09-04 17:05 UTC, nuno929 commented
> 上記もふまえても、job以外の $ref: company は削除して問題ないでしょうか？
大丈夫です！

↓の発言でしょうか？ 「DBとswaggerの定義は同じままに保ちたい」とは言っていないですね。
https://github.com/team-maker-developers/team-maker-api/pull/1#discussion_r319827728

上記の場合は、↓が理由です
・管理者と一般社員でPOSTするデータが変わるかは確定していないこと
・管理者と一般社員の分割は絶対に必要ではないこと

こういう原則がありますので、意識していただければと思います！
https://qiita.com/sesame525/items/fb2cfb23d0d7ef593014

2019-09-05 01:29 UTC, daisuke85a commented
@nuno929 
回答ありがとうございます！

>companyをまたぐユーザーはいないので、job以外の $ref: company は不要かと思います。

こちら対応していきます！

>上記のコメントは、↓の理由から発言しております。
>・管理者と一般社員でPOSTするデータが変わるかは確定していないこと
>・モデルの数は少ない方が望ましいこと

ありがとうございます！理解しました。

>YAGNI原則というものがありますので、意識していただければと思います！
>https://qiita.com/sesame525/items/fb2cfb23d0d7ef593014

こちらもありがとうございます！
知ってはいたものの、意識が低かったです💦意識していきます！

2019-09-05 03:12 UTC, nuno929 approved these changes
ご対応ありがとうございました！

2019-09-05 03:12 UTC, merged